YES = 'Yes'
NO = 'No'
GENDERS_LIST = ['Male', 'Female', 'Other']

REFERRAL_LIST = [
    'Career Event',
    'Company Website',
    'Employee Referral',
    'Job Board',
    'Print Advertisement',
    'Recruiter ',
    'Search Engine (Google, Bing, etc.)',
    'Social Media',
    'University Recruiting'
]

ETHNICITY_LIST = [
    'American Indian/Alaskan Native',
    'Asian',
    'Black or African American',
    'Hispanic or Latino',
    'Native Hawaiian or Other Pacific Island',
    'Two or More Races',
    'Undeclared',
    'White'
]

DISABILITY_LIST = [
    'No disability',
    'Not willing to answer',
    'Yes, with a disability (or previously had a disability)'
]

INDUSTRY_LIST = [
    'Construction/Mining',
    'Custom Services\u00A0',
    'Distribution Service',
    'Finance Services',
    'Food Industry',
    'Goods Transportation',
    'Government',
    'Health Care',
    'Human Resources',
    'Information Technology Services',
    'Manufacturing - Nondurable',
    'Marketing Services',
    'Oil and Gas',
    'Other Food Service',
    'Other - Noncore Generic',
    'Package Supplies',
    'Project Services',
    'Promotion Services\u00A0',
    'Raw Material Supply',
    'Real Estate',
    'Services - Generic',
    'Services - Nonprofit',
    'Spare Parts',
    'Telecommunications',
    'Textile industry',
    'Training Services',
    'Transportation',
    'Utilities',
    'Utility Company',
    'Wholesale',
    'Wholesale/Retail Trade'
]

GRADUATION_STATUS = [
    'Actively Pursuing the Degree',
    'Completed - Non Degree Program',
    'Graduated - Degree Received',
    'No Longer Pursuing the Degree'
]

DEGREE_MAJORS = [
    'Accounting',
    'Advertising/ Media',
    'Agricultural Economics',
    'Agriculture/ Aquaculture/ Forestry',
    'Agriculture Engineering',
    'Air Conditioning/Refrigeration',
    'Airline Operation/ Airport Management',
    'Airplane Mechanics',
    'Animal Science/ Veterinary',
    'Anthropology',
    'Architecture',
    'Art/ Design/ Creative/ Multimedia',
    'Aviation/ Aeronautics/ Astronautics/ Aircraft Engineering',
    'Baking Science \u0026 Technology',
    'Behavioral Science',
    'Bioengineering/ Biomedical Engineering',
    'Biological Science',
    'Biology',
    'BioTechnology',
    'Business Studies/ Administration/ Management',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Commerce',
    'Commercial Design',
    'Communications/ Mass Communications',
    'Computer/ Telecommunication Engineering',
    'Computer Science/ Information Technology',
    'Counseling/ Guidance/ Vocational Career Development',
    'Criminal Justice',
    'Data Processing',
    'Dentistry',
    'Economics',
    'Education/ Teaching/ Training',
    'Electrical/ Electronic Engineering',
    'Engineering',
    'English/ English Literature',
    'Environmental/ Health/ Safety Engineering,',
    'Environmental Health',
    'Finance/ Accountancy/ Banking',
    'Food \u0026 Beverage Services Management',
    'Food Science \u0026 Technology',
    'Food Technology/ Nutrition/ Dietetic',
    'Geographical Science',
    'Geology/ Geophysics',
    'Grain Processing',
    'Health/ Medicine/ Medical Science',
    'History',
    'Home Economics',
    'Hospitality/ Travel/ Tourism/ Hotel Management',
    'Humanities/ Liberal Arts',
    'Human Resource Management',
    'Industrial/ Labor Relations',
    'Industrial Design',
    'Industrial Engineering',
    'Industrial Technology',
    'Information Systems',
    'International Relations',
    'Journalism',
    'Law/ Juris Doctorate',
    'Library Management',
    'Life Sciences',
    'Linguistics/ Languages',
    'Logistic/ Transportation',
    'Marine Engineering',
    'Maritime Studies',
    'Marketing',
    'Material Science Engineering',
    'Mathematics',
    'Mechanical/ Electromechanical Engineering',
    'Medical Technology',
    'Metal Fabrication/ Tool \u0026 Die/ Welding Engineering',
    'Microbiology',
    'Mining/Mineral Engineering',
    'Music/ Performing Arts Studies',
    'Not Applicable',
    'Nursing',
    'Optometry',
    'Package Engineering',
    'Packaging',
    'Personal Services',
    'Petroleum/ Oil/ Gas Engineering',
    'Pharmacy/ Pharmacology',
    'Philosophy',
    'Physical Therapy/ Physiotherapy',
    'Physics',
    'Political Science',
    'Pre-Law',
    'Pre-Med',
    'Production/ Operations',
    'Property Development/ Real Estate Management',
    'Protective Services \u0026 Management',
    'Psychology',
    'Quantitative Analysis',
    'Radio/ TV/ Film',
    'Retailing',
    'Safety \u0026 Construction',
    'Science',
    'Secretarial',
    'Selling/ Sales Management/ Retail',
    'Social Science/ Sociology',
    'Social Welfare',
    'Sociology',
    'Speech Pathology',
    'Sports Science \u0026 Management',
    'Statistics',
    'Taxation',
    'Textile/ Fashion Design',
    'Theology',
    'Traffic',
    'Urban Studies'
]

# Incomplete List
DEGREE_TYPES = [
    'Bachelors Degree (Bachelor of Science or Arts)'
]

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"
